executable("tests") {
  sources = [
    "codegen_llvm/llvm_ir_emitter_test.cc",
    "ir/ir_common_test.cc",
    "test_main.cc",
    "util/test_util.cc",
    "util/test_util.h",
  ]

  configs += [
    "//src:alcy_config",
    "//src:win_sys_libs",
  ]
  deps = [
    "//src:libs",
    "//third_party/doctest",
    "//third_party/fpag",
  ]
}
