source_set("codegen_llvm") {
  sources = [
    "common.h",
    "declaration.h",
    "llvm_ir_emitter.cc",
    "llvm_ir_emitter.h",
  ]
  deps = [ "//src:base_modules" ]
  public_deps = [
    "//src/ir",
    "//third_party/llvm",
  ]

  # if (is_debug) {
  #   defines = [
  #     "LLVM_ENABLE_STATS",
  #     "LLVM_ENABLE_DUMP",
  #     "LLVM_ENABLE_ASSERTIONS=1",
  #   ]
  #   # System installed libc++ (release) will be used on macos
  #   if (!is_mac) {
  #     defines += [ "LLVM_ENABLE_ABI_BREAKING_CHECKS=1" ]
  #   } else {
  #     defines += [ "LLVM_ENABLE_ABI_BREAKING_CHECKS=0" ]
  #   }
  # } else {
  #   defines = [
  #     "LLVM_ENABLE_ABI_BREAKING_CHECKS=0",
  #     "LLVM_ENABLE_ASSERTIONS=0",
  #   ]
  # }

  configs += [ "//src:alcy_config" ]
}
