name: CI

on:
  push:
    branches: [main]
    paths: &ci_paths
      - src/**
      - tests/**
      - benchmarks/**
      - third_party/**
      - scripts/**
      - .github/workflows/**
      - .clang-tidy
      - CPPLINT.cfg
      - uv.lock
  pull_request:
    branches: [main]
    paths: *ci_paths
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-debug:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: debug

  build-release:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: release

  summary:
    needs: [build-debug, build-release]
    if: always()
    uses: ./.github/workflows/generate-summary.yaml
    with:
      artifact_pattern: "*"
