name: CI

on:
  push:
    branches: [main]
    paths: &ci_paths
      - src/**
      - tests/**
      - benchmarks/**
      - third_party/**
      - scripts/**
      - .github/workflows/ci.yaml
      - xmake.lua
      - .clang-tidy
      - CPPLINT.cfg
      - uv.lock
  pull_request:
    branches: [main]
    paths: *ci_paths
  workflow_dispatch:

jobs:
  build:
    name: Build and test (${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
        cc: [clang]
        cxx: [clang++]
        llvm_version: [22.1.8]
        os:
          - ubuntu-24.04
          - macos-26
          - windows-2025-vs2026
        include:
          - os: ubuntu-24.04
            plat: linux
            arch: x86_64
            stdlib: libc++
            static_stdlib: true
          - os: macos-26
            plat: macosx
            arch: arm64
            stdlib: libc++
            static_stdlib: false
          - os: windows-2025-vs2026
            plat: windows
            arch: x64
            stdlib: msvc
            static_stdlib: false
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      COLORTERM: 256color
      XMAKE_COLORTERM: 256color
      XMAKE_ROOT: y
      basename: "alcy"
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup build environment
        uses: pug523/actions/cxx-setup@eacbdb6dc5006a90076a84f7f3547265c90472c9
        with:
          os: ${{ runner.os }}
          plat: ${{ matrix.plat }}
          arch: ${{ matrix.arch }}
          build_type: ${{ matrix.build_type }}
          llvm_version: ${{ matrix.llvm_version }}

      - name: Cache LLVM tag
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: scripts/.llvm_tag_cache
          key: ${{ runner.os }}-${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.cc }}-${{ matrix.cxx }}-${{ matrix.build_type }}-llvm_tag_cache

      - name: Configure
        shell: bash
        run: |
          xmake config -y \
            -m ${{ matrix.build_type }} \
            --tests=y \
            --benchmarks=y \
            --toolchain=clang \
            --llvm=y \
            --cache-llvm=y \
            --download-llvm=y \
            --build-llvm=n \
            --stdlib="${{ matrix.stdlib }}" \
            --static-stdlib="${{ matrix.static_stdlib }}" \
            --component_kind="static" \
            --sanitizers=y \
            --libunwind=y \
            -p "${{ matrix.plat }}" \
            -a "${{ matrix.arch }}"

      - name: Build
        shell: bash
        run: |
          xmake build -w

      - name: Build tests and run
        shell: bash
        run: xmake run tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: build/${{ matrix.plat }}/${{ matrix.arch }}/**

      - name: Analyze statically
        if: runner.os == 'Linux' && matrix.build_type == 'debug'
        shell: bash
        run: |
          xmake check api
          xmake check clang
          xmake lint

      - name: Package & Generate Checksum
        shell: bash
        run: |
          FILE="${{ env.basename }}-${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.build_type }}.tar.gz"

          tar -czvf "$FILE" -C build/${{ matrix.plat }}/${{ matrix.arch }} .

          if command -v sha256sum &> /dev/null; then
            sha256sum "$FILE" > "${FILE}.sha256"
          else
            shasum -a 256 "$FILE" > "${FILE}.sha256"
          fi

      - name: Upload checksum artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: checksum-${{ matrix.plat }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: "*.sha256"

  summary:
    needs: build
    uses: ./.github/workflows/generate-summary.yaml
