name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: release
      is_release: true

  publish:
    needs: build-release
    runs-on: ubuntu-24.04
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228
        with:
          files: |
            */*.tar.gz
            */*.zip
            */*.sha256
          draft: true
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: publish
    if: always()
    uses: ./.github/workflows/generate-summary.yaml
    with:
      artifact_pattern: "*"
